"""attendance table

Revision ID: 8611ce2d50ac
Revises: b8c996f09fb9
Create Date: 2019-03-18 23:17:13.939886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8611ce2d50ac'
down_revision = 'b8c996f09fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bs_group', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
